version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nine-auth
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
